##
# Flags for C++ compiler
##
CXXFLAGS += -std=c++11 -Wall

example_bitmap_operation : ../../src/image_function.cpp ../../src/FileOperation/bitmap.cpp

.PHONY: clean
clean:
	$(RM) example_bitmap_operation
