##
# Flags for C++ compiler
##
CXXFLAGS += -std=c++11 -Wall

example_blob_detection : ../../src/image_function.cpp ../../src/blob_detection.cpp ../../src/FileOperation/bitmap.cpp

.PHONY: clean
clean:
	$(RM) example_blob_detection
