##
# Flags for C++ compiler
##
CXXFLAGS += -std=c++11 -Wall

example_median_filter : ../../Library/image_function.cpp ../../Library/filtering.cpp ../../Library/FileOperation/bitmap.cpp

.PHONY: clean
clean:
	$(RM) example_median_filter
