##
# Flags for C++ compiler
##
CXXFLAGS += -std=c++11 -Wall

example_blob_detection : ../../Library/image_function.cpp ../../Library/blob_detection.cpp ../../Library/FileOperation/bitmap.cpp

.PHONY: clean
clean:
	$(RM) example_blob_detection
