##
# Flags for C++ compiler
##
CXXFLAGS += -std=c++11 -Wall

example_median_filter : ../../src/image_function.cpp ../../src/filtering.cpp ../../src/FileOperation/bitmap.cpp

.PHONY: clean
clean:
	$(RM) example_median_filter
