##
# Flags for C++ compiler
##
CXXFLAGS += -std=c++11 -Wall

example_bitmap_operation : ../../Library/image_function.cpp ../../Library/FileOperation/bitmap.cpp

.PHONY: clean
clean:
	$(RM) example_bitmap_operation
